// Function to convert ISO 2-letter code to flag emoji
String countryCodeToEmoji(String isoCode) {
  if (isoCode.length != 2) return '';
  final int firstLetter = isoCode.codeUnitAt(0) - 0x41 + 0x1F1E6;
  final int secondLetter = isoCode.codeUnitAt(1) - 0x41 + 0x1F1E6;
  return String.fromCharCode(firstLetter) + String.fromCharCode(secondLetter);
}

List<Map<String, String>> countryCodesWithFlags = [
  {
    'id': '1',
    'name': 'Afghanistan',
    'code': 'AF',
    'iso3Code': 'AFG',
    'dial_code': '+93',
  },
  {
    'id': '2',
    'name': 'Åland Islands',
    'code': 'AX',
    'iso3Code': 'ALA',
    'dial_code': '+358',
  },
  {
    'id': '3',
    'name': 'Albania',
    'code': 'AL',
    'iso3Code': 'ALB',
    'dial_code': '+355',
  },
  {
    'id': '4',
    'name': 'Algeria',
    'code': 'DZ',
    'iso3Code': 'DZA',
    'dial_code': '+213',
  },
  {
    'id': '5',
    'name': 'American Samoa',
    'code': 'AS',
    'iso3Code': 'ASM',
    'dial_code': '+1684',
  },
  {
    'id': '6',
    'name': 'Andorra',
    'code': 'AD',
    'iso3Code': 'AND',
    'dial_code': '+376',
  },
  {
    'id': '7',
    'name': 'Angola',
    'code': 'AO',
    'iso3Code': 'AGO',
    'dial_code': '+244',
  },
  {
    'id': '8',
    'name': 'Anguilla',
    'code': 'AI',
    'iso3Code': 'AIA',
    'dial_code': '+1264',
  },
  {
    'id': '9',
    'name': 'Antarctica',
    'code': 'AQ',
    'iso3Code': 'ATA',
    'dial_code': '+672',
  },
  {
    'id': '10',
    'name': 'Antigua and Barbuda',
    'code': 'AG',
    'iso3Code': 'ATG',
    'dial_code': '+1268',
  },
  {
    'id': '11',
    'name': 'Argentina',
    'code': 'AR',
    'iso3Code': 'ARG',
    'dial_code': '+54',
  },
  {
    'id': '12',
    'name': 'Armenia',
    'code': 'AM',
    'iso3Code': 'ARM',
    'dial_code': '+374',
  },
  {
    'id': '13',
    'name': 'Aruba',
    'code': 'AW',
    'iso3Code': 'ABW',
    'dial_code': '+297',
  },
  {
    'id': '14',
    'name': 'Australia',
    'code': 'AU',
    'iso3Code': 'AUS',
    'dial_code': '+61',
  },
  {
    'id': '15',
    'name': 'Austria',
    'code': 'AT',
    'iso3Code': 'AUT',
    'dial_code': '+43',
  },
  {
    'id': '16',
    'name': 'Azerbaijan',
    'code': 'AZ',
    'iso3Code': 'AZE',
    'dial_code': '+994',
  },
  {
    'id': '17',
    'name': 'Bahamas',
    'code': 'BS',
    'iso3Code': 'BHS',
    'dial_code': '+1242',
  },
  {
    'id': '18',
    'name': 'Bahrain',
    'code': 'BH',
    'iso3Code': 'BHR',
    'dial_code': '+973',
  },
  {
    'id': '19',
    'name': 'Bangladesh',
    'code': 'BD',
    'iso3Code': 'BGD',
    'dial_code': '+880',
  },
  {
    'id': '20',
    'name': 'Barbados',
    'code': 'BB',
    'iso3Code': 'BRB',
    'dial_code': '+1246',
  },
  {
    'id': '21',
    'name': 'Belarus',
    'code': 'BY',
    'iso3Code': 'BLR',
    'dial_code': '+375',
  },
  {
    'id': '22',
    'name': 'Belgium',
    'code': 'BE',
    'iso3Code': 'BEL',
    'dial_code': '+32',
  },
  {
    'id': '23',
    'name': 'Belize',
    'code': 'BZ',
    'iso3Code': 'BLZ',
    'dial_code': '+501',
  },
  {
    'id': '24',
    'name': 'Benin',
    'code': 'BJ',
    'iso3Code': 'BEN',
    'dial_code': '+229',
  },
  {
    'id': '25',
    'name': 'Bermuda',
    'code': 'BM',
    'iso3Code': 'BMU',
    'dial_code': '+1441',
  },
  {
    'id': '26',
    'name': 'Bhutan',
    'code': 'BT',
    'iso3Code': 'BTN',
    'dial_code': '+975',
  },
  {
    'id': '27',
    'name': 'Bolivia',
    'code': 'BO',
    'iso3Code': 'BOL',
    'dial_code': '+591',
  },
  {
    'id': '28',
    'name': 'Bosnia and Herzegovina',
    'code': 'BA',
    'iso3Code': 'BIH',
    'dial_code': '+387',
  },
  {
    'id': '29',
    'name': 'Botswana',
    'code': 'BW',
    'iso3Code': 'BWA',
    'dial_code': '+267',
  },
  {
    'id': '30',
    'name': 'Bouvet Island',
    'code': 'BV',
    'iso3Code': 'BVT',
    'dial_code': '+47',
  },
  {
    'id': '31',
    'name': 'Brazil',
    'code': 'BR',
    'iso3Code': 'BRA',
    'dial_code': '+55',
  },
  {
    'id': '32',
    'name': 'British Indian Ocean Territory',
    'code': 'IO',
    'iso3Code': 'IOT',
    'dial_code': '+246',
  },
  {
    'id': '33',
    'name': 'Brunei Darussalam',
    'code': 'BN',
    'iso3Code': 'BRN',
    'dial_code': '+673',
  },
  {
    'id': '34',
    'name': 'Bulgaria',
    'code': 'BG',
    'iso3Code': 'BGR',
    'dial_code': '+359',
  },
  {
    'id': '35',
    'name': 'Burkina Faso',
    'code': 'BF',
    'iso3Code': 'BFA',
    'dial_code': '+226',
  },
  {
    'id': '36',
    'name': 'Burundi',
    'code': 'BI',
    'iso3Code': 'BDI',
    'dial_code': '+257',
  },
  {
    'id': '37',
    'name': 'Cambodia',
    'code': 'KH',
    'iso3Code': 'KHM',
    'dial_code': '+855',
  },
  {
    'id': '38',
    'name': 'Cameroon',
    'code': 'CM',
    'iso3Code': 'CMR',
    'dial_code': '+237',
  },
  {
    'id': '39',
    'name': 'Canada',
    'code': 'CA',
    'iso3Code': 'CAN',
    'dial_code': '+1',
  },
  {
    'id': '40',
    'name': 'Cape Verde',
    'code': 'CV',
    'iso3Code': 'CPV',
    'dial_code': '+238',
  },
  {
    'id': '41',
    'name': 'Cayman Islands',
    'code': 'KY',
    'iso3Code': 'CYM',
    'dial_code': '+1345',
  },
  {
    'id': '42',
    'name': 'Central African Republic',
    'code': 'CF',
    'iso3Code': 'CAF',
    'dial_code': '+236',
  },
  {
    'id': '43',
    'name': 'Chad',
    'code': 'TD',
    'iso3Code': 'TCD',
    'dial_code': '+235',
  },
  {
    'id': '44',
    'name': 'Chile',
    'code': 'CL',
    'iso3Code': 'CHL',
    'dial_code': '+56',
  },
  {
    'id': '45',
    'name': 'China',
    'code': 'CN',
    'iso3Code': 'CHN',
    'dial_code': '+86',
  },
  {
    'id': '46',
    'name': 'Christmas Island',
    'code': 'CX',
    'iso3Code': 'CXR',
    'dial_code': '+61',
  },
  {
    'id': '47',
    'name': 'Cocos (Keeling) Islands',
    'code': 'CC',
    'iso3Code': 'CCK',
    'dial_code': '+61',
  },
  {
    'id': '48',
    'name': 'Colombia',
    'code': 'CO',
    'iso3Code': 'COL',
    'dial_code': '+57',
  },
  {
    'id': '49',
    'name': 'Comoros',
    'code': 'KM',
    'iso3Code': 'COM',
    'dial_code': '+269',
  },
  {
    'id': '50',
    'name': 'Congo',
    'code': 'CG',
    'iso3Code': 'COG',
    'dial_code': '+242',
  },
  {
    'id': '51',
    'name': 'Congo, The Democratic Republic of the',
    'code': 'CD',
    'iso3Code': 'COD',
    'dial_code': '+243',
  },
  {
    'id': '52',
    'name': 'Cook Islands',
    'code': 'CK',
    'iso3Code': 'COK',
    'dial_code': '+682',
  },
  {
    'id': '53',
    'name': 'Costa Rica',
    'code': 'CR',
    'iso3Code': 'CRI',
    'dial_code': '+506',
  },
  {
    'id': '54',
    'name': "Côte d'Ivoire",
    'code': 'CI',
    'iso3Code': 'CIV',
    'dial_code': '+225',
  },
  {
    'id': '55',
    'name': 'Croatia',
    'code': 'HR',
    'iso3Code': 'HRV',
    'dial_code': '+385',
  },
  {
    'id': '56',
    'name': 'Cuba',
    'code': 'CU',
    'iso3Code': 'CUB',
    'dial_code': '+53',
  },
  {
    'id': '57',
    'name': 'Cyprus',
    'code': 'CY',
    'iso3Code': 'CYP',
    'dial_code': '+357',
  },
  {
    'id': '58',
    'name': 'Czech Republic',
    'code': 'CZ',
    'iso3Code': 'CZE',
    'dial_code': '+420',
  },
  {
    'id': '59',
    'name': 'Denmark',
    'code': 'DK',
    'iso3Code': 'DNK',
    'dial_code': '+45',
  },
  {
    'id': '60',
    'name': 'Djibouti',
    'code': 'DJ',
    'iso3Code': 'DJI',
    'dial_code': '+253',
  },
  {
    'id': '61',
    'name': 'Dominica',
    'code': 'DM',
    'iso3Code': 'DMA',
    'dial_code': '+1767',
  },
  {
    'id': '62',
    'name': 'Dominican Republic',
    'code': 'DO',
    'iso3Code': 'DOM',
    'dial_code': '+1',
  },
  {
    'id': '63',
    'name': 'Ecuador',
    'code': 'EC',
    'iso3Code': 'ECU',
    'dial_code': '+593',
  },
  {
    'id': '64',
    'name': 'Egypt',
    'code': 'EG',
    'iso3Code': 'EGY',
    'dial_code': '+20',
  },
  {
    'id': '65',
    'name': 'El Salvador',
    'code': 'SV',
    'iso3Code': 'SLV',
    'dial_code': '+503',
  },
  {
    'id': '66',
    'name': 'Equatorial Guinea',
    'code': 'GQ',
    'iso3Code': 'GNQ',
    'dial_code': '+240',
  },
  {
    'id': '67',
    'name': 'Eritrea',
    'code': 'ER',
    'iso3Code': 'ERI',
    'dial_code': '+291',
  },
  {
    'id': '68',
    'name': 'Estonia',
    'code': 'EE',
    'iso3Code': 'EST',
    'dial_code': '+372',
  },
  {
    'id': '69',
    'name': 'Ethiopia',
    'code': 'ET',
    'iso3Code': 'ETH',
    'dial_code': '+251',
  },
  {
    'id': '70',
    'name': 'Falkland Islands (Malvinas)',
    'code': 'FK',
    'iso3Code': 'FLK',
    'dial_code': '+500',
  },
  {
    'id': '71',
    'name': 'Faroe Islands',
    'code': 'FO',
    'iso3Code': 'FRO',
    'dial_code': '+298',
  },
  {
    'id': '72',
    'name': 'Fiji',
    'code': 'FJ',
    'iso3Code': 'FJI',
    'dial_code': '+679',
  },
  {
    'id': '73',
    'name': 'Finland',
    'code': 'FI',
    'iso3Code': 'FIN',
    'dial_code': '+358',
  },
  {
    'id': '74',
    'name': 'France',
    'code': 'FR',
    'iso3Code': 'FRA',
    'dial_code': '+33',
  },
  {
    'id': '75',
    'name': 'French Guiana',
    'code': 'GF',
    'iso3Code': 'GUF',
    'dial_code': '+594',
  },
  {
    'id': '76',
    'name': 'French Polynesia',
    'code': 'PF',
    'iso3Code': 'PYF',
    'dial_code': '+689',
  },
  {
    'id': '77',
    'name': 'French Southern Territories',
    'code': 'TF',
    'iso3Code': 'ATF',
    'dial_code': '+262',
  },
  {
    'id': '78',
    'name': 'Gabon',
    'code': 'GA',
    'iso3Code': 'GAB',
    'dial_code': '+241',
  },
  {
    'id': '79',
    'name': 'Gambia',
    'code': 'GM',
    'iso3Code': 'GMB',
    'dial_code': '+220',
  },
  {
    'id': '80',
    'name': 'Georgia',
    'code': 'GE',
    'iso3Code': 'GEO',
    'dial_code': '+995',
  },
  {
    'id': '81',
    'name': 'Germany',
    'code': 'DE',
    'iso3Code': 'DEU',
    'dial_code': '+49',
  },
  {
    'id': '82',
    'name': 'Ghana',
    'code': 'GH',
    'iso3Code': 'GHA',
    'dial_code': '+233',
  },
  {
    'id': '83',
    'name': 'Gibraltar',
    'code': 'GI',
    'iso3Code': 'GIB',
    'dial_code': '+350',
  },
  {
    'id': '84',
    'name': 'Greece',
    'code': 'GR',
    'iso3Code': 'GRC',
    'dial_code': '+30',
  },
  {
    'id': '85',
    'name': 'Greenland',
    'code': 'GL',
    'iso3Code': 'GRL',
    'dial_code': '+299',
  },
  {
    'id': '86',
    'name': 'Grenada',
    'code': 'GD',
    'iso3Code': 'GRD',
    'dial_code': '+1473',
  },
  {
    'id': '87',
    'name': 'Guadeloupe',
    'code': 'GP',
    'iso3Code': 'GLP',
    'dial_code': '+590',
  },
  {
    'id': '88',
    'name': 'Guam',
    'code': 'GU',
    'iso3Code': 'GUM',
    'dial_code': '+1671',
  },
  {
    'id': '89',
    'name': 'Guatemala',
    'code': 'GT',
    'iso3Code': 'GTM',
    'dial_code': '+502',
  },
  {
    'id': '90',
    'name': 'Guernsey',
    'code': 'GG',
    'iso3Code': 'GGY',
    'dial_code': '+44',
  },
  {
    'id': '91',
    'name': 'Guinea',
    'code': 'GN',
    'iso3Code': 'GIN',
    'dial_code': '+224',
  },
  {
    'id': '92',
    'name': 'Guinea-Bissau',
    'code': 'GW',
    'iso3Code': 'GNB',
    'dial_code': '+245',
  },
  {
    'id': '93',
    'name': 'Guyana',
    'code': 'GY',
    'iso3Code': 'GUY',
    'dial_code': '+592',
  },
  {
    'id': '94',
    'name': 'Haiti',
    'code': 'HT',
    'iso3Code': 'HTI',
    'dial_code': '+509',
  },
  {
    'id': '95',
    'name': 'Heard Island and McDonald Islands',
    'code': 'HM',
    'iso3Code': 'HMD',
    'dial_code': '+0',
  },
  {
    'id': '96',
    'name': 'Holy See (Vatican City State)',
    'code': 'VA',
    'iso3Code': 'VAT',
    'dial_code': '+379',
  },
  {
    'id': '97',
    'name': 'Honduras',
    'code': 'HN',
    'iso3Code': 'HND',
    'dial_code': '+504',
  },
  {
    'id': '98',
    'name': 'Hong Kong',
    'code': 'HK',
    'iso3Code': 'HKG',
    'dial_code': '+852',
  },
  {
    'id': '99',
    'name': 'Hungary',
    'code': 'HU',
    'iso3Code': 'HUN',
    'dial_code': '+36',
  },
  {
    'id': '100',
    'name': 'Iceland',
    'code': 'IS',
    'iso3Code': 'ISL',
    'dial_code': '+354',
  },
  {
    'id': '101',
    'name': 'India',
    'code': 'IN',
    'iso3Code': 'IND',
    'dial_code': '+91',
  },
  {
    'id': '102',
    'name': 'Indonesia',
    'code': 'ID',
    'iso3Code': 'IDN',
    'dial_code': '+62',
  },
  {
    'id': '103',
    'name': 'Iran, Islamic Republic of',
    'code': 'IR',
    'iso3Code': 'IRN',
    'dial_code': '+98',
  },
  {
    'id': '104',
    'name': 'Iraq',
    'code': 'IQ',
    'iso3Code': 'IRQ',
    'dial_code': '+964',
  },
  {
    'id': '105',
    'name': 'Ireland',
    'code': 'IE',
    'iso3Code': 'IRL',
    'dial_code': '+353',
  },
  {
    'id': '106',
    'name': 'Isle of Man',
    'code': 'IM',
    'iso3Code': 'IMN',
    'dial_code': '+44',
  },
  {
    'id': '107',
    'name': 'Israel',
    'code': 'IL',
    'iso3Code': 'ISR',
    'dial_code': '+972',
  },
  {
    'id': '108',
    'name': 'Italy',
    'code': 'IT',
    'iso3Code': 'ITA',
    'dial_code': '+39',
  },
  {
    'id': '109',
    'name': 'Jamaica',
    'code': 'JM',
    'iso3Code': 'JAM',
    'dial_code': '+1876',
  },
  {
    'id': '110',
    'name': 'Japan',
    'code': 'JP',
    'iso3Code': 'JPN',
    'dial_code': '+81',
  },
  {
    'id': '111',
    'name': 'Jersey',
    'code': 'JE',
    'iso3Code': 'JEY',
    'dial_code': '+44',
  },
  {
    'id': '112',
    'name': 'Jordan',
    'code': 'JO',
    'iso3Code': 'JOR',
    'dial_code': '+962',
  },
  {
    'id': '113',
    'name': 'Kazakhstan',
    'code': 'KZ',
    'iso3Code': 'KAZ',
    'dial_code': '+7',
  },
  {
    'id': '114',
    'name': 'Kenya',
    'code': 'KE',
    'iso3Code': 'KEN',
    'dial_code': '+254',
  },
  {
    'id': '115',
    'name': 'Kiribati',
    'code': 'KI',
    'iso3Code': 'KIR',
    'dial_code': '+686',
  },
  {
    'id': '116',
    'name': "Korea, Democratic People's Republic of",
    'code': 'KP',
    'iso3Code': 'PRK',
    'dial_code': '+850',
  },
  {
    'id': '117',
    'name': 'Korea, Republic of',
    'code': 'KR',
    'iso3Code': 'KOR',
    'dial_code': '+82',
  },
  {
    'id': '118',
    'name': 'Kosovo',
    'code': 'XK',
    'iso3Code': 'KOS',
    'dial_code': '+383',
  }, // Often included despite not being officially UN recognized by all
  {
    'id': '119',
    'name': 'Kuwait',
    'code': 'KW',
    'iso3Code': 'KWT',
    'dial_code': '+965',
  },
  {
    'id': '120',
    'name': 'Kyrgyzstan',
    'code': 'KG',
    'iso3Code': 'KGZ',
    'dial_code': '+996',
  },
  {
    'id': '121',
    'name': "Lao People's Democratic Republic",
    'code': 'LA',
    'iso3Code': 'LAO',
    'dial_code': '+856',
  },
  {
    'id': '122',
    'name': 'Latvia',
    'code': 'LV',
    'iso3Code': 'LVA',
    'dial_code': '+371',
  },
  {
    'id': '123',
    'name': 'Lebanon',
    'code': 'LB',
    'iso3Code': 'LBN',
    'dial_code': '+961',
  },
  {
    'id': '124',
    'name': 'Lesotho',
    'code': 'LS',
    'iso3Code': 'LSO',
    'dial_code': '+266',
  },
  {
    'id': '125',
    'name': 'Liberia',
    'code': 'LR',
    'iso3Code': 'LBR',
    'dial_code': '+231',
  },
  {
    'id': '126',
    'name': 'Libya',
    'code': 'LY',
    'iso3Code': 'LBY',
    'dial_code': '+218',
  },
  {
    'id': '127',
    'name': 'Liechtenstein',
    'code': 'LI',
    'iso3Code': 'LIE',
    'dial_code': '+423',
  },
  {
    'id': '128',
    'name': 'Lithuania',
    'code': 'LT',
    'iso3Code': 'LTU',
    'dial_code': '+370',
  },
  {
    'id': '129',
    'name': 'Luxembourg',
    'code': 'LU',
    'iso3Code': 'LUX',
    'dial_code': '+352',
  },
  {
    'id': '130',
    'name': 'Macao',
    'code': 'MO',
    'iso3Code': 'MAC',
    'dial_code': '+853',
  },
  {
    'id': '131',
    'name': 'Macedonia, The Former Yugoslav Republic of',
    'code': 'MK',
    'iso3Code': 'MKD',
    'dial_code': '+389',
  },
  {
    'id': '132',
    'name': 'Madagascar',
    'code': 'MG',
    'iso3Code': 'MDG',
    'dial_code': '+261',
  },
  {
    'id': '133',
    'name': 'Malawi',
    'code': 'MW',
    'iso3Code': 'MWI',
    'dial_code': '+265',
  },
  {
    'id': '134',
    'name': 'Malaysia',
    'code': 'MY',
    'iso3Code': 'MYS',
    'dial_code': '+60',
  },
  {
    'id': '135',
    'name': 'Maldives',
    'code': 'MV',
    'iso3Code': 'MDV',
    'dial_code': '+960',
  },
  {
    'id': '136',
    'name': 'Mali',
    'code': 'ML',
    'iso3Code': 'MLI',
    'dial_code': '+223',
  },
  {
    'id': '137',
    'name': 'Malta',
    'code': 'MT',
    'iso3Code': 'MLT',
    'dial_code': '+356',
  },
  {
    'id': '138',
    'name': 'Marshall Islands',
    'code': 'MH',
    'iso3Code': 'MHL',
    'dial_code': '+692',
  },
  {
    'id': '139',
    'name': 'Martinique',
    'code': 'MQ',
    'iso3Code': 'MTQ',
    'dial_code': '+596',
  },
  {
    'id': '140',
    'name': 'Mauritania',
    'code': 'MR',
    'iso3Code': 'MRT',
    'dial_code': '+222',
  },
  {
    'id': '141',
    'name': 'Mauritius',
    'code': 'MU',
    'iso3Code': 'MUS',
    'dial_code': '+230',
  },
  {
    'id': '142',
    'name': 'Mayotte',
    'code': 'YT',
    'iso3Code': 'MYT',
    'dial_code': '+262',
  },
  {
    'id': '143',
    'name': 'Mexico',
    'code': 'MX',
    'iso3Code': 'MEX',
    'dial_code': '+52',
  },
  {
    'id': '144',
    'name': 'Micronesia, Federated States of',
    'code': 'FM',
    'iso3Code': 'FSM',
    'dial_code': '+691',
  },
  {
    'id': '145',
    'name': 'Moldova, Republic of',
    'code': 'MD',
    'iso3Code': 'MDA',
    'dial_code': '+373',
  },
  {
    'id': '146',
    'name': 'Monaco',
    'code': 'MC',
    'iso3Code': 'MCO',
    'dial_code': '+377',
  },
  {
    'id': '147',
    'name': 'Mongolia',
    'code': 'MN',
    'iso3Code': 'MNG',
    'dial_code': '+976',
  },
  {
    'id': '148',
    'name': 'Montenegro',
    'code': 'ME',
    'iso3Code': 'MNE',
    'dial_code': '+382',
  },
  {
    'id': '149',
    'name': 'Montserrat',
    'code': 'MS',
    'iso3Code': 'MSR',
    'dial_code': '+1664',
  },
  {
    'id': '150',
    'name': 'Morocco',
    'code': 'MA',
    'iso3Code': 'MAR',
    'dial_code': '+212',
  },
  {
    'id': '151',
    'name': 'Mozambique',
    'code': 'MZ',
    'iso3Code': 'MOZ',
    'dial_code': '+258',
  },
  {
    'id': '152',
    'name': 'Myanmar',
    'code': 'MM',
    'iso3Code': 'MMR',
    'dial_code': '+95',
  },
  {
    'id': '153',
    'name': 'Namibia',
    'code': 'NA',
    'iso3Code': 'NAM',
    'dial_code': '+264',
  },
  {
    'id': '154',
    'name': 'Nauru',
    'code': 'NR',
    'iso3Code': 'NRU',
    'dial_code': '+674',
  },
  {
    'id': '155',
    'name': 'Nepal',
    'code': 'NP',
    'iso3Code': 'NPL',
    'dial_code': '+977',
  },
  {
    'id': '156',
    'name': 'Netherlands',
    'code': 'NL',
    'iso3Code': 'NLD',
    'dial_code': '+31',
  },
  {
    'id': '157',
    'name': 'Netherlands Antilles',
    'code': 'AN',
    'iso3Code': 'ANT',
    'dial_code': '+599',
  },
  {
    'id': '158',
    'name': 'New Caledonia',
    'code': 'NC',
    'iso3Code': 'NCL',
    'dial_code': '+687',
  },
  {
    'id': '159',
    'name': 'New Zealand',
    'code': 'NZ',
    'iso3Code': 'NZL',
    'dial_code': '+64',
  },
  {
    'id': '160',
    'name': 'Nicaragua',
    'code': 'NI',
    'iso3Code': 'NIC',
    'dial_code': '+505',
  },
  {
    'id': '161',
    'name': 'Niger',
    'code': 'NE',
    'iso3Code': 'NER',
    'dial_code': '+227',
  },
  {
    'id': '162',
    'name': 'Nigeria',
    'code': 'NG',
    'iso3Code': 'NGA',
    'dial_code': '+234',
  },
  {
    'id': '163',
    'name': 'Niue',
    'code': 'NU',
    'iso3Code': 'NIU',
    'dial_code': '+683',
  },
  {
    'id': '164',
    'name': 'Norfolk Island',
    'code': 'NF',
    'iso3Code': 'NFK',
    'dial_code': '+672',
  },
  {
    'id': '165',
    'name': 'Northern Mariana Islands',
    'code': 'MP',
    'iso3Code': 'MNP',
    'dial_code': '+1670',
  },
  {
    'id': '166',
    'name': 'Norway',
    'code': 'NO',
    'iso3Code': 'NOR',
    'dial_code': '+47',
  },
  {
    'id': '167',
    'name': 'Oman',
    'code': 'OM',
    'iso3Code': 'OMN',
    'dial_code': '+968',
  },
  {
    'id': '168',
    'name': 'Pakistan',
    'code': 'PK',
    'iso3Code': 'PAK',
    'dial_code': '+92',
  },
  {
    'id': '169',
    'name': 'Palau',
    'code': 'PW',
    'iso3Code': 'PLW',
    'dial_code': '+680',
  },
  {
    'id': '170',
    'name': 'Palestinian Territory, Occupied',
    'code': 'PS',
    'iso3Code': 'PSE',
    'dial_code': '+970',
  },
  {
    'id': '171',
    'name': 'Panama',
    'code': 'PA',
    'iso3Code': 'PAN',
    'dial_code': '+507',
  },
  {
    'id': '172',
    'name': 'Papua New Guinea',
    'code': 'PG',
    'iso3Code': 'PNG',
    'dial_code': '+675',
  },
  {
    'id': '173',
    'name': 'Paraguay',
    'code': 'PY',
    'iso3Code': 'PRY',
    'dial_code': '+595',
  },
  {
    'id': '174',
    'name': 'Peru',
    'code': 'PE',
    'iso3Code': 'PER',
    'dial_code': '+51',
  },
  {
    'id': '175',
    'name': 'Philippines',
    'code': 'PH',
    'iso3Code': 'PHL',
    'dial_code': '+63',
  },
  {
    'id': '176',
    'name': 'Pitcairn',
    'code': 'PN',
    'iso3Code': 'PCN',
    'dial_code': '+64',
  },
  {
    'id': '177',
    'name': 'Poland',
    'code': 'PL',
    'iso3Code': 'POL',
    'dial_code': '+48',
  },
  {
    'id': '178',
    'name': 'Portugal',
    'code': 'PT',
    'iso3Code': 'PRT',
    'dial_code': '+351',
  },
  {
    'id': '179',
    'name': 'Puerto Rico',
    'code': 'PR',
    'iso3Code': 'PRI',
    'dial_code': '+1939',
  },
  {
    'id': '180',
    'name': 'Puerto Rico',
    'code': 'PR',
    'iso3Code': 'PRI',
    'dial_code': '+1787',
  }, // Duplicate dial code for PR, kept for consistency with original list
  {
    'id': '181',
    'name': 'Qatar',
    'code': 'QA',
    'iso3Code': 'QAT',
    'dial_code': '+974',
  },
  {
    'id': '182',
    'name': 'Romania',
    'code': 'RO',
    'iso3Code': 'ROU',
    'dial_code': '+40',
  },
  {
    'id': '183',
    'name': 'Russian Federation',
    'code': 'RU',
    'iso3Code': 'RUS',
    'dial_code': '+7',
  },
  {
    'id': '184',
    'name': 'Rwanda',
    'code': 'RW',
    'iso3Code': 'RWA',
    'dial_code': '+250',
  },
  {
    'id': '185',
    'name': 'Réunion',
    'code': 'RE',
    'iso3Code': 'REU',
    'dial_code': '+262',
  },
  {
    'id': '186',
    'name': 'Saint Barthélemy',
    'code': 'BL',
    'iso3Code': 'BLM',
    'dial_code': '+590',
  },
  {
    'id': '187',
    'name': 'Saint Helena, Ascension and Tristan Da Cunha',
    'code': 'SH',
    'iso3Code': 'SHN',
    'dial_code': '+290',
  },
  {
    'id': '188',
    'name': 'Saint Kitts and Nevis',
    'code': 'KN',
    'iso3Code': 'KNA',
    'dial_code': '+1869',
  },
  {
    'id': '189',
    'name': 'Saint Lucia',
    'code': 'LC',
    'iso3Code': 'LCA',
    'dial_code': '+1758',
  },
  {
    'id': '190',
    'name': 'Saint Martin (French Part)',
    'code': 'MF',
    'iso3Code': 'MAF',
    'dial_code': '+590',
  },
  {
    'id': '191',
    'name': 'Saint Pierre and Miquelon',
    'code': 'PM',
    'iso3Code': 'SPM',
    'dial_code': '+508',
  },
  {
    'id': '192',
    'name': 'Saint Vincent and the Grenadines',
    'code': 'VC',
    'iso3Code': 'VCT',
    'dial_code': '+1784',
  },
  {
    'id': '193',
    'name': 'Samoa',
    'code': 'WS',
    'iso3Code': 'WSM',
    'dial_code': '+685',
  },
  {
    'id': '194',
    'name': 'San Marino',
    'code': 'SM',
    'iso3Code': 'SMR',
    'dial_code': '+378',
  },
  {
    'id': '195',
    'name': 'Sao Tome and Principe',
    'code': 'ST',
    'iso3Code': 'STP',
    'dial_code': '+239',
  },
  {
    'id': '196',
    'name': 'Saudi Arabia',
    'code': 'SA',
    'iso3Code': 'SAU',
    'dial_code': '+966',
  },
  {
    'id': '197',
    'name': 'Senegal',
    'code': 'SN',
    'iso3Code': 'SEN',
    'dial_code': '+221',
  },
  {
    'id': '198',
    'name': 'Serbia',
    'code': 'RS',
    'iso3Code': 'SRB',
    'dial_code': '+381',
  },
  {
    'id': '199',
    'name': 'Seychelles',
    'code': 'SC',
    'iso3Code': 'SYC',
    'dial_code': '+248',
  },
  {
    'id': '200',
    'name': 'Sierra Leone',
    'code': 'SL',
    'iso3Code': 'SLE',
    'dial_code': '+232',
  },
  {
    'id': '201',
    'name': 'Singapore',
    'code': 'SG',
    'iso3Code': 'SGP',
    'dial_code': '+65',
  },
  {
    'id': '202',
    'name': 'Slovakia',
    'code': 'SK',
    'iso3Code': 'SVK',
    'dial_code': '+421',
  },
  {
    'id': '203',
    'name': 'Slovenia',
    'code': 'SI',
    'iso3Code': 'SVN',
    'dial_code': '+386',
  },
  {
    'id': '204',
    'name': 'Solomon Islands',
    'code': 'SB',
    'iso3Code': 'SLB',
    'dial_code': '+677',
  },
  {
    'id': '205',
    'name': 'Somalia',
    'code': 'SO',
    'iso3Code': 'SOM',
    'dial_code': '+252',
  },
  {
    'id': '206',
    'name': 'South Africa',
    'code': 'ZA',
    'iso3Code': 'ZAF',
    'dial_code': '+27',
  },
  {
    'id': '207',
    'name': 'South Sudan',
    'code': 'SS',
    'iso3Code': 'SSD',
    'dial_code': '+211',
  },
  {
    'id': '208',
    'name': 'South Georgia and the South Sandwich Islands',
    'code': 'GS',
    'iso3Code': 'SGS',
    'dial_code': '+500',
  },
  {
    'id': '209',
    'name': 'Spain',
    'code': 'ES',
    'iso3Code': 'ESP',
    'dial_code': '+34',
  },
  {
    'id': '210',
    'name': 'Sri Lanka',
    'code': 'LK',
    'iso3Code': 'LKA',
    'dial_code': '+94',
  },
  {
    'id': '211',
    'name': 'Sudan',
    'code': 'SD',
    'iso3Code': 'SDN',
    'dial_code': '+249',
  },
  {
    'id': '212',
    'name': 'Suriname',
    'code': 'SR',
    'iso3Code': 'SUR',
    'dial_code': '+597',
  },
  {
    'id': '213',
    'name': 'Svalbard and Jan Mayen',
    'code': 'SJ',
    'iso3Code': 'SJM',
    'dial_code': '+47',
  },
  {
    'id': '214',
    'name': 'Swaziland',
    'code': 'SZ',
    'iso3Code': 'SWZ',
    'dial_code': '+268',
  },
  {
    'id': '215',
    'name': 'Sweden',
    'code': 'SE',
    'iso3Code': 'SWE',
    'dial_code': '+46',
  },
  {
    'id': '216',
    'name': 'Switzerland',
    'code': 'CH',
    'iso3Code': 'CHE',
    'dial_code': '+41',
  },
  {
    'id': '217',
    'name': 'Syrian Arab Republic',
    'code': 'SY',
    'iso3Code': 'SYR',
    'dial_code': '+963',
  },
  {
    'id': '218',
    'name': 'Taiwan, Province of China',
    'code': 'TW',
    'iso3Code': 'TWN',
    'dial_code': '+886',
  },
  {
    'id': '219',
    'name': 'Tajikistan',
    'code': 'TJ',
    'iso3Code': 'TJK',
    'dial_code': '+992',
  },
  {
    'id': '220',
    'name': 'Tanzania, United Republic of',
    'code': 'TZ',
    'iso3Code': 'TZA',
    'dial_code': '+255',
  },
  {
    'id': '221',
    'name': 'Thailand',
    'code': 'TH',
    'iso3Code': 'THA',
    'dial_code': '+66',
  },
  {
    'id': '222',
    'name': 'Timor-Leste',
    'code': 'TL',
    'iso3Code': 'TLS',
    'dial_code': '+670',
  },
  {
    'id': '223',
    'name': 'Togo',
    'code': 'TG',
    'iso3Code': 'TGO',
    'dial_code': '+228',
  },
  {
    'id': '224',
    'name': 'Tokelau',
    'code': 'TK',
    'iso3Code': 'TKL',
    'dial_code': '+690',
  },
  {
    'id': '225',
    'name': 'Tonga',
    'code': 'TO',
    'iso3Code': 'TON',
    'dial_code': '+676',
  },
  {
    'id': '226',
    'name': 'Trinidad and Tobago',
    'code': 'TT',
    'iso3Code': 'TTO',
    'dial_code': '+1868',
  },
  {
    'id': '227',
    'name': 'Tunisia',
    'code': 'TN',
    'iso3Code': 'TUN',
    'dial_code': '+216',
  },
  {
    'id': '228',
    'name': 'Turkey',
    'code': 'TR',
    'iso3Code': 'TUR',
    'dial_code': '+90',
  },
  {
    'id': '229',
    'name': 'Turkmenistan',
    'code': 'TM',
    'iso3Code': 'TKM',
    'dial_code': '+993',
  },
  {
    'id': '230',
    'name': 'Turks and Caicos Islands',
    'code': 'TC',
    'iso3Code': 'TCA',
    'dial_code': '+1649',
  },
  {
    'id': '231',
    'name': 'Tuvalu',
    'code': 'TV',
    'iso3Code': 'TUV',
    'dial_code': '+688',
  },
  {
    'id': '232',
    'name': 'Uganda',
    'code': 'UG',
    'iso3Code': 'UGA',
    'dial_code': '+256',
  },
  {
    'id': '233',
    'name': 'Ukraine',
    'code': 'UA',
    'iso3Code': 'UKR',
    'dial_code': '+380',
  },
  {
    'id': '234',
    'name': 'United Arab Emirates',
    'code': 'AE',
    'iso3Code': 'ARE',
    'dial_code': '+971',
  },
  {
    'id': '235',
    'name': 'United Kingdom',
    'code': 'GB',
    'iso3Code': 'GBR',
    'dial_code': '+44',
  },
  {
    'id': '236',
    'name': 'United States',
    'code': 'US',
    'iso3Code': 'USA',
    'dial_code': '+1',
  },
  {
    'id': '237',
    'name': 'Uruguay',
    'code': 'UY',
    'iso3Code': 'URY',
    'dial_code': '+598',
  },
  {
    'id': '238',
    'name': 'Uzbekistan',
    'code': 'UZ',
    'iso3Code': 'UZB',
    'dial_code': '+998',
  },
  {
    'id': '239',
    'name': 'Vanuatu',
    'code': 'VU',
    'iso3Code': 'VUT',
    'dial_code': '+678',
  },
  {
    'id': '240',
    'name': 'Venezuela, Bolivarian Republic of',
    'code': 'VE',
    'iso3Code': 'VEN',
    'dial_code': '+58',
  },
  {
    'id': '241',
    'name': 'Viet Nam',
    'code': 'VN',
    'iso3Code': 'VNM',
    'dial_code': '+84',
  },
  {
    'id': '242',
    'name': 'Virgin Islands, British',
    'code': 'VG',
    'iso3Code': 'VGB',
    'dial_code': '+1284',
  },
  {
    'id': '243',
    'name': 'Virgin Islands, U.S.',
    'code': 'VI',
    'iso3Code': 'VIR',
    'dial_code': '+1340',
  },
  {
    'id': '244',
    'name': 'Wallis and Futuna',
    'code': 'WF',
    'iso3Code': 'WLF',
    'dial_code': '+681',
  },
  {
    'id': '245',
    'name': 'Yemen',
    'code': 'YE',
    'iso3Code': 'YEM',
    'dial_code': '+967',
  },
  {
    'id': '246',
    'name': 'Zambia',
    'code': 'ZM',
    'iso3Code': 'ZMB',
    'dial_code': '+260',
  },
  {
    'id': '247',
    'name': 'Zimbabwe',
    'code': 'ZW',
    'iso3Code': 'ZWE',
    'dial_code': '+263',
  },
].map((item) => {...item, 'flag': countryCodeToEmoji(item['code']!)}).toList();
